export default[
	{
		training_id:1,
		training_room:'A101',
		training_num:'第四实训楼',
		training_building:"A栋",
		training_floor:1,
		address:'第四实训楼A栋A101室'
	},
	{
		training_id:2,
		training_room:'A201',
		training_num:'第四实训楼',
		training_building:"A栋",
		training_floor:2,
		address:'第四实训楼A栋A201室'
	},
	{
		training_id:3,
		training_room:'A301',
		training_num:'第四实训楼',
		training_building:"A栋",
		training_floor:3,
		address:'第四实训楼A栋A301室'
	},
	{
		training_id:4,
		training_room:'A401',
		training_num:'第四实训楼',
		training_building:"A栋",
		training_floor:4,
		address:'第四实训楼A栋A401室'
	},
	{
		training_id:5,
		training_room:'A501',
		training_num:'第四实训楼',
		training_building:"A栋",
		training_floor:5,
		address:'第四实训楼A栋A501室'
	},
	{
		training_id:6,
		training_room:'B101',
		training_num:'第四实训楼',
		training_building:"B栋",
		training_floor:1,
		address:'第四实训楼B栋B101室'
	},
	{
		training_id:7,
		training_room:'C101',
		training_num:'第四实训楼',
		training_building:"C栋",
		training_floor:1,
		address:'第四实训楼C栋C101室'
	},
	{
		training_id:8,
		training_room:'D101',
		training_num:'第四实训楼',
		training_building:"A栋",
		training_floor:1,
		address:'第四实训楼D栋D101室'
	},
	{
		training_id:9,
		training_room:'A101',
		training_num:'第三实训楼',
		training_building:"A栋",
		training_floor:1,
		address:'第三实训楼A栋A101室'
	}
]